### ISSUE TITLE
Чем это отличается от Трелло?

### ISSUE THREAD

**Issue by StopGamer** [eillasti/jso#4]

**Comment by StopGamer** [comment]
Ага понял, вафля - интерфейс для гитов

**Comment by eillasti** [comment]
да, плюс выглядит разметка приличней намного намного

On 23 June 2015 at 17:52, StopGamer notifications@github.com wrote:

> Ага понял, вафля - интерфейс для гитов
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/eillasti/jso/issues/4#issuecomment-114554932.

## 

Denis Kornilov,
Master in Banking and Finance student
University of St. Gallen
